apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumulusairaisvc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cumulusairaisvc
  template:
    metadata:
      labels:
        name: cumulusairaisvc
    spec:
      serviceAccountName: cumulusairaisvc
      containers:
        - name: cumulusairaisvc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cumulusairaisvc"
