apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cumulusairaisvcs.cumulusair.com
spec:
  group: cumulusair.com
  names:
    kind: CumulusAirAiSvc
    listKind: CumulusAirAiSvcList
    plural: cumulusairaisvcs
    singular: cumulusairaisvc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
